Update UI
Isaacwilliam4/INSyT pull request #36
Opened 2024-04-15 21:55 UTC by brightlightkim

2024-04-15 22:47 UTC, dtingey requested changes

2024-04-15 22:47 UTC, dtingey commented on db-server/server.js
We got rid of db-server. Use `insyt-server` instead. Make sure to pull the most recent changes.

2024-04-16 16:22 UTC, brightlightkim commented on db-server/server.js
It has been changed now! :)

2024-04-16 17:00 UTC, dtingey approved these changes

2024-04-16 17:00 UTC, merged